language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 74efe1706086cd36c9f25cdfe5b1f8630200e8ae
 local_dir: dist
 on:
   branch: master